# Master Control Panel Values for Payday Platform

frontend:
  image:
    repository: 618015514540.dkr.ecr.us-east-1.amazonaws.com/payday/frontend
    tag: latest
  replicaCount: 1

api:
  image:
    repository: 618015514540.dkr.ecr.us-east-1.amazonaws.com/payday/api
    tag: latest
  replicaCount: 1

worker:
  image:
    repository: 618015514540.dkr.ecr.us-east-1.amazonaws.com/payday/worker
    tag: latest
  replicaCount: 1

postgresql:
  image:
    repository: postgres
    tag: 15-alpine
  dbName: payday_ledger
  user: payday_admin
  password: vault_secret_pass
