apiVersion: apps/v1
kind: Deployment
metadata:
  name: payday-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: payday-postgres
  template:
    metadata:
      labels:
        app: payday-postgres
    spec:
      containers:
        - name: postgres
          image: '{{ .Values.postgresql.image.repository | default "postgres" }}:{{ .Values.postgresql.image.tag | default "15-alpine" }}'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.dbName | default "payday_ledger" }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | default "payday_admin" }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | default "vault_secret_pass" }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
