apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis # Must match your service selector
  template:
    metadata:
      labels:
        app: redis # Must match your service selector
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
